version: '3.3'

services:
    redis_managerbundle_php:
        image: dh.rinsvent.ru/php8dev
        container_name: redis_managerbundle_php
        volumes:
            - ./:/app
        environment:
            USE_COMPOSER_SCRIPTS: 0
        depends_on:
            - redis_managerbundle_redis
    redis_managerbundle_redis:
        image: dh.rinsvent.ru/redis
        container_name: redis_managerbundle_redis
        command: redis-server --requirepass password123
networks:
    default:
        external:
            name: full-project
